### PR TITLE
Replace underscore with amp-* modules

### PR DESCRIPTION
**Pull request by wizardzloy**
Leave the underscore as a devDependency for test file, since there is no replacement for ```_.pick``` function available yet.

### CODE REVIEW

**Comment by drewloomer** [comment]
I came here to add this. Can we get this merged in? I don't want to have to include underscore in my project.

**Comment by wraithgar** [comment]
Yeah let's go ahead and get pick removed and made it a clean break! http://amp.ampersandjs.com/#amp-pick

**Comment by wizardzloy** [comment]
Will do that tomorrow and update the pull request

**Comment by wizardzloy** [comment]
Updated, no underscore anymore

**Comment by wraithgar** [comment]
+1 looks good, tests pass locally for me too.

**Comment by HenrikJoreteg** [comment]
+1 here too, i'm ready to ship this. this should be safe to do as a patch update right?

**Comment by wraithgar** [comment]
Yep this is just an underlying dependency change w/ parity of features.

**Comment by HenrikJoreteg** [comment]
published as `1.0.7`

**Comment by HenrikJoreteg** [comment]
thanks @wizardzloy!

**Pull request merged**
