### PR TITLE
Trigger true

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
Includes all fixes in: https://github.com/AmpersandJS/ampersand-router/pull/14 trying to get tests passing.

I think we shoudl do a 3.0 release that merges this and includes lodash PR.

### CODE REVIEW

**Comment by lukekarrys** [comment]
@HenrikJoreteg The lodash stuff was already published in `2.0.1`, so I merged the latest master into this branch. After that:

- I converted the new merged tests to use `AmpHistory` and `AmpRouter` like the others
- I used `restartHistoryWithoutPushState()` in the `loadUrl` test and that made it work for me locally

The tests all pass for me now, and I'm +1 on this.

**Comment by wraithgar** [comment]
Ok yeah thanks @lukekarrys thanks for getting this ironed out.  +1

**Comment by lukekarrys** [comment]
Published as `v3.0.0`

**Comment by HenrikJoreteg** [comment]
Thanks guys!!

**Comment by fyockm** [comment]
Trying to get `ampersand-cli` up to date with lodash and all the new ampersand versions, but this ampersand-router@3.0.0 seems to break navigation. Can one of you point me in the right direction for what needs to be updated? I'll commit a work branch to that repo shortly (assuming my privileges are in place).

**Comment by wraithgar** [comment]
The breaking change was due to a default setting changing.  afaik it should still work for the example app. Go ahead and make your branch that uses 3.0.0 and has broken navigation and I'll check it out and help debug.

**Comment by fyockm** [comment]
see #43. thanks @wraithgar

**Pull request merged**
